version: '3.1'

services:

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
            - 3306:3306
        volumes:
            - sql-persist:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8010:80
volumes:
    sql-persist:
